#!/usr/bin/env python3
"""Lab03-04  Hamming code corrector  (Template-04.dig: In[7] -> Output[7])

Writes lab04_hamming.pla: for each of the 10 BCD codewords in the lab table,
the codeword itself plus its 7 single-bit corruptions all map to the clean
codeword; the other 48 inputs are don't cares.

Bit order: table position 1 (p1) is the bus MSB In6 ... position 7 (m4) is In0.
Use --pos1-lsb to generate the reversed convention instead.
"""
import argparse, sys

# table 1 of the lab sheet: positions 1..7 = p1 p2 m1 p3 m2 m3 m4
TABLE = ["0000000", "1101001", "0101010", "1000011", "1001100",
         "0100101", "1100110", "0001111", "1110000", "0011001"]

ap = argparse.ArgumentParser()
ap.add_argument("--pos1-lsb", action="store_true", help="position 1 = In0 instead of In6")
ap.add_argument("-o", default="lab04_hamming.pla")
a = ap.parse_args()

rows = []
for cw in TABLE:
    for flip in range(-1, 7):
        bad = list(cw)
        if flip >= 0:
            bad[flip] = "1" if bad[flip] == "0" else "0"
        bad = "".join(bad)
        if a.pos1_lsb:
            rows.append((bad[::-1], cw[::-1]))
        else:
            rows.append((bad, cw))

with open(a.o, "w") as f:
    f.write("# Lab03-04  Hamming(7,4) single-error corrector for BCD  (generated by make_hamming_pla.py%s)\n"
            % (" --pos1-lsb" if a.pos1_lsb else ""))
    f.write("# In6..In0 = table positions %s\n" % ("7..1" if a.pos1_lsb else "1..7"))
    f.write("#map Output=O6,O5,O4,O3,O2,O1,O0\n.i 7\n.o 7\n.ilb In6 In5 In4 In3 In2 In1 In0\n.ob O6 O5 O4 O3 O2 O1 O0\n.type fd\n")
    for i, o in rows:
        f.write("%s %s\n" % (i, o))
    f.write(".e\n")
print("%s: %d rows" % (a.o, len(rows)))
